version: 2

defaults: &defaults
  steps:
    - checkout
    - run: |
        pip install codecov
        coverage run test.py
        codecov

jobs:
  test-against-pypy2:
    docker:
      - image: pypy:2-6.0-slim
    <<: *defaults
  test-against-pypy3:
    docker:
      - image: pypy:3-6.0-slim
    <<: *defaults
  test-against-python2:
    docker:
      - image: python:2.7.15-slim-stretch
    <<: *defaults
  test-against-python3:
    docker:
      - image: python:3.7-alpine3.8
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
    - test-against-pypy2
    - test-against-pypy3
    - test-against-python2
    - test-against-python3
